###
POST https://localhost/api/auth/login
Content-Type: application/json

{
    "username":"6281935155404"
}

###
POST https://localhost/api/auth/verify
Content-Type: application/json

{
    "username":"6281935155404",
    "password":"321654"
}

###
POST https://localhost/api/auth/register
Content-Type: application/json

{
    "username":"6281935155404"
}

###
POST https://localhost/api/auth/logout
Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIyMDIzLTEyLTEzVDA3OjEzOjM2LjU1NVoiLCJyb2xlIjpbInVzZXIiXX0.cq6AxlY5QCGEPi2LKLTaQajf9w7Yg5vfUfZ7Aqdg9GukxFYFoSrLe7oeuStAoDubwnuWkATvFI8Apxev9En_fEPk3QqUOX0vokcZJ6CksDiLyqAUXhk30HrIvM9XqG4XaFr3zG7RcFWcC3M-nUyJwXx6Z_B5FqlBtw_D7C3ECfyHy2fkw-OvDKs2-zh6cIUazMPTPnq2KecIB4uAA5R7gJ_OXc1Er8U7eYlaqVI7pN0q8vgZzneHhwsRPL-ARIkJlBuiJK_FZ9ZKLJAYyT28eqboHaFKqze2sbhaI0x78AYYpMKgOaYmmMm5E6_VrmbuBc6ZCMWxZdgabUQ_h4i-fw

###
POST https://localhost/api/auth/refresh
Authorization: Bearer eyJhbGciOiJQUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIyMDIzLTEyLTE0VDA2OjEzOjM2LjU1N1oiLCJyb2xlIjpbInJlZnJlc2giXX0.gAOqfMQ5e1XmuK_G0-dOI3LoyEvPVu-iT0xIzi4EXui6GNZ7kNpETGve5aO9_UKFdHcTamcFv_cTTQLHISBJzLEQck25Hbtu_ecQIJIk5VHfnaN6EtaWCo7cNo0p-c-2hCfQWidPZwQJQ_jd8U8M5XfyWvqpjmlGTU16j6BM2fYdg6zJFyF7UJMlhGuq4TstgEmLcbSXLFJMch43NCAm5JrxO-sypbMWI_4eSeSb96x_MUkvao6rYsa7u5lJCAPiP-Z5hrIN67ah4Q4jIfvPuyFeoOThM_-tToBKf8kf_Bio3y0gpefOhNozWwMFu6kSVA8njW6nCXEixKygQhq0kQ

###
POST https://localhost/api/auth/revoke
Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIyMDIzLTEyLTEzVDA3OjEzOjM2LjU1NVoiLCJyb2xlIjpbInVzZXIiXX0.cq6AxlY5QCGEPi2LKLTaQajf9w7Yg5vfUfZ7Aqdg9GukxFYFoSrLe7oeuStAoDubwnuWkATvFI8Apxev9En_fEPk3QqUOX0vokcZJ6CksDiLyqAUXhk30HrIvM9XqG4XaFr3zG7RcFWcC3M-nUyJwXx6Z_B5FqlBtw_D7C3ECfyHy2fkw-OvDKs2-zh6cIUazMPTPnq2KecIB4uAA5R7gJ_OXc1Er8U7eYlaqVI7pN0q8vgZzneHhwsRPL-ARIkJlBuiJK_FZ9ZKLJAYyT28eqboHaFKqze2sbhaI0x78AYYpMKgOaYmmMm5E6_VrmbuBc6ZCMWxZdgabUQ_h4i-fw
